### ISSUE TITLE
Проверка версий библиотек на соответсвие

### ISSUE THREAD

**Issue by sasha1004** [sberdevices/smart_app_framework#210]
Для версий питона 3.8 устанавливается markupsafe=2.1.0
Что приводит к фатальному запуску приложения.
Помогла откатка версии до markupsafe=2.0.1
[https://github.com/aws/aws-sam-cli/issues/3661](https://github.com/aws/aws-sam-cli/issues/3661)

**Comment by Dan1lD** [comment]
#207
